# Generated by Django 4.2.16 on 2024-10-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_PAID", "Not Paid"),
                    ("PARTIALLY_PAID", "Partially Paid"),
                    ("PAID", "Paid"),
                ],
                default="NOT_PAID",
                max_length=20,
            ),
        ),
    ]
