# Generated by Django 4.2.16 on 2024-10-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_manager", "0002_alter_invoice_paid_amount_alter_invoice_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
